---
Style/AsciiComments:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Naming/FileName:
  Enabled: false
SignalException:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Style/FrozenStringLiteralComment:
  Enabled: false
