cmdargs:
  severity: warning
  error-limit: 50
  color: true
  env:
    neovim: true
  stdin_display_name: stdin

policies:
  # Experimental
  ProhibitUnusedVariable:
    enabled: true
  ProhibitImplicitScopeVariable:
    enabled: true
  ProhibitAbbreviationOption:
    enabled: false
