version: 2
root-markers:
- .git/

tools:
  rego-opa: &rego-opa
    format-command: 'opa fmt'
    lint-command: 'opa check'
    lint-formats:
    - '%m: %f:%l: %m'
    - '%f:%l: %m'
  sh-shellcheck: &sh-shellcheck
    format-command: 'shfmt'
    lint-command: 'shellcheck -f gcc -x'
    lint-source: 'shellcheck'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'
  sh-shfmt: &sh-shfmt
    format-command: 'shfmt -ci -s -bn'
    format-stdin: true

languages:
  rego:
  - <<: *rego-opa
  sh:
  - <<: *sh-shellcheck
  - <<: *sh-shfmt
