version: 2
root-markers:
- .git/

tools:
  rego-opa: &rego-opa
    format-command: 'opa fmt'
    lint-command: 'opa check'
    lint-formats:
    - '%m: %f:%l: %m'
    - '%f:%l: %m'

languages:
  rego:
  - <<: *rego-opa
