version: 2
root-markers:
- .git/

tools:
  rego-opa: &rego-opa
    format-command: 'opa fmt'
    lint-command: 'opa check'
    lint-formats:
    - '%m: %f:%l: %m'
    - '%f:%l: %m'
  lua-lua-format: &lua-lua-format
    format-command: 'lua-format -i'
    format-stdin: true

languages:
  rego:
  - <<: *rego-opa
  lua:
  - <<: *lua-lua-format
