local:
- name: zsh-hooks
  description: My zsh hooks
  directory: ~/.zsh/hooks
  plugin:
    if: |
      [[ $SHELL == *zsh* ]]
    sources:
    - '*.zsh'
- name: zsh
  description: My zsh scripts
  directory: ~/.zsh
  plugin:
    if: |
      [[ $SHELL == *zsh* ]]
    sources:
    - '[0-9]*.zsh'
    snippet: |
      # Use dynamic PATH management for better flexibility
      # Note: Order matters - first added = highest priority
      path_add ~/bin
      path_add /opt/homebrew/bin
      path_add ~/.local/share/aquaproj-aqua/bin
      path_add ~/ghq/bin
      path_add /usr/local/bin
      path_add /usr/sbin
      path_add ~/.local/bin
      path_add ~/.tmux/bin
      path_add '$NPM_CONFIG_PREFIX/bin'
      path_add /usr/local/opt/libpq/bin
      path_add /usr/local/opt/llvm/bin
      path_add /opt/homebrew/opt/openjdk@17/bin
      path_add '$HOME/.krew/bin'
      path_add '~/Library/Application Support/Coursier/bin'
      path_add ~/.cargo/bin
      path_add ~/.tmux/plugins/tpm/bin
