local:
- name: zsh-hooks
  description: My zsh hooks
  directory: ~/.zsh/hooks
  plugin:
    if: |
      [[ $SHELL == *zsh* ]]
    sources:
    - '*.zsh'
- name: zsh
  description: My zsh scripts
  directory: ~/.zsh
  plugin:
    if: |
      [[ $SHELL == *zsh* ]]
    sources:
    - '[0-9]*.zsh'
    snippet: |
      # Use dynamic PATH management for better flexibility
      # Using append mode for clarity - written order matches PATH priority
      # First entry = highest priority, last entry = lowest priority
      path_add ~/bin append
      path_add ~/.local/share/aquaproj-aqua/bin append
      path_add /opt/homebrew/bin append
      path_add ~/ghq/bin append
      path_add /usr/local/bin append
      path_add /usr/sbin append
      path_add ~/.local/bin append
      path_add ~/.tmux/bin append
      path_add '$NPM_CONFIG_PREFIX/bin' append
      path_add /usr/local/opt/libpq/bin append
      path_add /usr/local/opt/llvm/bin append
      path_add /opt/homebrew/opt/openjdk@17/bin append
      path_add '$HOME/.krew/bin' append
      path_add '~/Library/Application Support/Coursier/bin' append
      path_add ~/.cargo/bin append
      path_add ~/.tmux/plugins/tpm/bin append
