gui:
  # stuff relating to the UI
  # how many lines you scroll by
  scrollHeight: 2
  # enable scrolling past the bottom
  scrollPastBottom: true
  theme:
    activeBorderColor:
    - yellow
    - bold
    inactiveBorderColor:
    - white
    optionsTextColor:
    - blue
  commitLength:
    show: true
git:
  merging:
    # only applicable to unix users
    manualCommit: false
  skipHookPrefix: WIP
update:
  # can be: prompt | background | never
  method: prompt
  days: 14
reporting: 'off'
confirmOnQuit: false
