confirmonquit: false
git:
  merging:
    manualcommit: false
  skiphookprefix: WIP
gui:
  commitlength:
    show: true
  scrollheight: 2
  scrollpastbottom: true
  theme:
    activebordercolor:
    - yellow
    - bold
    inactivebordercolor:
    - white
    optionstextcolor:
    - blue
reporting: "off"
startuppopupversion: 1
update:
  days: 14
  method: prompt
